server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/admin_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  application:
    name: AUTH-SERVICE

jwt:
  secret: 5367566B59703373357638792F423F4528482B4D6251655468576D5A71347437

  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/