server:
  port: 8081

spring:
  datasource:
<<<<<<< HEAD
    url: jdbc:postgresql://localhost:5432/e-commerce_db
=======
    url: jdbc:postgresql://localhost:5432/admin_db
>>>>>>> 9bf39969ed17497e7ad66bd8295cf16d64befd56
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  application:
    name: AUTH-SERVICE

jwt:
  secret: 5367566B59703373357638792F423F4528482B4D6251655468576D5A71347437
