server:
  port: 8888

#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: AUTH-SERVICE
#          uri: lb://AUTH-SERVICE
#          predicates:
#            - Path=/auth/**


spring:
    cloud:
      gateway:
        globalcors:
          cors-configurations:
            '[/**]':
              allowedOrigins: "http://localhost:3000/"
              allowedMethods:
                - GET
                - PUT
                - POST
    application:
      name: ECOMMERCE-GATEWAY

jwt:
  secret: 5367566B59703373357638792F423F4528482B4D6251655468576D5A71347437



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/